/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BirdAwayControl: typeof import('./src/components/BirdAwayControl.vue')['default']
    CameraPlayer: typeof import('./src/components/CameraPlayer.vue')['default']
    DebugController: typeof import('./src/components/DebugController.vue')['default']
    FrameSwitchOver: typeof import('./src/components/FrameSwitchOver.vue')['default']
    IBxsDownArrow: typeof import('~icons/bxs/down-arrow')['default']
    IBxsLeftArrow: typeof import('~icons/bxs/left-arrow')['default']
    IBxsRightArrow: typeof import('~icons/bxs/right-arrow')['default']
    IBxsUpArrow: typeof import('~icons/bxs/up-arrow')['default']
    IIcomoonFreeSwitch: typeof import('~icons/icomoon-free/switch')['default']
    IMdiArrowDropUp: typeof import('~icons/mdi/arrow-drop-up')['default']
    IVaadinTimeBackward: typeof import('~icons/vaadin/time-backward')['default']
    PantiltControl: typeof import('./src/components/PantiltControl.vue')['default']
    PointConfigDrawer: typeof import('./src/components/PointConfigDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateAlarmDialog: typeof import('./src/components/TemplateAlarmDialog.vue')['default']
    TemplateDialog: typeof import('./src/components/TemplateDialog.vue')['default']
    TemplateSearchDialog: typeof import('./src/components/TemplateSearchDialog.vue')['default']
    ToolbarController: typeof import('./src/components/ToolbarController.vue')['default']
    VideoController: typeof import('./src/components/VideoController.vue')['default']
  }
}
