/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BirdAwayControl: typeof import('./src/components/BirdAwayControl.vue')['default']
    CameraPlayer: typeof import('./src/components/CameraPlayer.vue')['default']
    DebugController: typeof import('./src/components/DebugController.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FrameSwitchOver: typeof import('./src/components/FrameSwitchOver.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IBxsDownArrow: typeof import('~icons/bxs/down-arrow')['default']
    IBxsLeftArrow: typeof import('~icons/bxs/left-arrow')['default']
    IBxsRightArrow: typeof import('~icons/bxs/right-arrow')['default']
    IBxsUpArrow: typeof import('~icons/bxs/up-arrow')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IIcomoonFreeSwitch: typeof import('~icons/icomoon-free/switch')['default']
    IMdiArrowDropUp: typeof import('~icons/mdi/arrow-drop-up')['default']
    IVaadinTimeBackward: typeof import('~icons/vaadin/time-backward')['default']
    PantiltControl: typeof import('./src/components/PantiltControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToolbarController: typeof import('./src/components/ToolbarController.vue')['default']
    VideoController: typeof import('./src/components/VideoController.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
